version: "3.8"

services:
  app:
    container_name: block-api
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh


  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
